// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class AppointmentDocument
{
    public Guid Id { get; set; }

    public Guid IdAppointment { get; set; }

    public Guid IdFile { get; set; }

    public virtual Appointment IdAppointmentNavigation { get; set; } = null!;

    public virtual StorageFile IdFileNavigation { get; set; } = null!;
}