// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class Appointment
{
    public Guid Id { get; set; }

    public Guid IdPacient { get; set; }

    public Guid IdDoctorSpecializations { get; set; }

    public int? Price { get; set; }

    public DateTime? DateAndTime { get; set; }

    public bool? IsCompleted { get; set; }

    public bool? IsApproved { get; set; }

    public virtual ICollection<AppointmentDocument> AppointmentDocuments { get; set; } = new List<AppointmentDocument>();

    public virtual ICollection<AppointmentInfo> AppointmentInfos { get; set; } = new List<AppointmentInfo>();

    public virtual DoctorsSpecialization IdDoctorSpecializationsNavigation { get; set; } = null!;

    public virtual Patient IdPacientNavigation { get; set; } = null!;

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}