// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class DoctorsSpecialization
{
    public Guid Id { get; set; }

    public Guid IdDoctor { get; set; }

    public int IdSpecialization { get; set; }

    public int? CustomPrice { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual Doctor IdDoctorNavigation { get; set; } = null!;

    public virtual Specialization IdSpecializationNavigation { get; set; } = null!;
}