// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class Doctor
{
    public Guid Id { get; set; }

    public int IdDegrees { get; set; }

    public virtual ICollection<DoctorProgram> DoctorPrograms { get; set; } = new List<DoctorProgram>();

    public virtual ICollection<DoctorsSpecialization> DoctorsSpecializations { get; set; } = new List<DoctorsSpecialization>();

    public virtual DoctoralDegree IdDegreesNavigation { get; set; } = null!;

    public virtual User IdNavigation { get; set; } = null!;

    public virtual ICollection<UnavailablePeriod> UnavailablePeriods { get; set; } = new List<UnavailablePeriod>();
}