// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class Notification
{
    public Guid Id { get; set; }

    public Guid IdUser { get; set; }

    public DateTime NotifyDate { get; set; }

    public int IdType { get; set; }

    public bool? IsRead { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual NotificationMessageType IdTypeNavigation { get; set; } = null!;

    public virtual User IdUserNavigation { get; set; } = null!;
}