// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class NotificationMessageType
{
    public int Id { get; set; }

    public string? Type { get; set; }

    public string? Message { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}