// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class Picture
{
    public Guid Id { get; set; }

    public Guid? IdUser { get; set; }

    public int? IdSpecialization { get; set; }

    public Guid IdFile { get; set; }

    public virtual StorageFile IdFileNavigation { get; set; } = null!;

    public virtual Specialization? IdSpecializationNavigation { get; set; }

    public virtual User? IdUserNavigation { get; set; }
}