// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class Specialization
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public int DefaultPrice { get; set; }

    public string? Description { get; set; }

    public virtual ICollection<DoctorsSpecialization> DoctorsSpecializations { get; set; } = new List<DoctorsSpecialization>();

    public virtual ICollection<Picture> Pictures { get; set; } = new List<Picture>();
}