// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class StorageFile
{
    public Guid Id { get; set; }

    public string FileUrl { get; set; } = null!;

    public int? FileSize { get; set; }

    public string FileType { get; set; } = null!;

    public string FileName { get; set; } = null!;

    public virtual ICollection<AppointmentDocument> AppointmentDocuments { get; set; } = new List<AppointmentDocument>();

    public virtual ICollection<Picture> Pictures { get; set; } = new List<Picture>();
}