// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class UnavailablePeriod
{
    public Guid Id { get; set; }

    public Guid IdDoctor { get; set; }

    public int IdReason { get; set; }

    public DateOnly StartingDay { get; set; }

    public DateOnly EndingDay { get; set; }

    public virtual Doctor IdDoctorNavigation { get; set; } = null!;

    public virtual UnavailableReason IdReasonNavigation { get; set; } = null!;
}