export default {
  Authenticate: "/auth",
  GetUserById: (id) => `/user/${id}`,
  GetUsers: "/users",
  RegisterUser: "/user/register",
  UpdateUser: "/user/update",
  DeactivateUser: (userId) => `/user/deactivate/${userId}`,
  DeleteUser: (userId) => `/user/delete/${userId}`,
  GetAllSpecializations: "/specialization/all",
  Profile: (userId) => `/patient/profile/${userId}`,
  DoctorProfile: (userId) => `/doctor/profile/${userId}`,
  UpdateProfile: "/patient/profile/update",
  GetAllDoctors: "/doctor/all",
  GetAllDegrees: "/degree/all",
  GetDoctorPrograms: "/program/doctor",
  CreateDoctorProgram: "/program/create",
  GetAllReasons: "/reason/all",
  UpdateDoctorProfile: "/doctor/profile/update",
  GetUnavailablePeriods: (doctorId) => `/appointment/unavailable/${doctorId}`,
  GetDoctorProgramByDay: (doctorId, date) =>
    `/appointment/program/${doctorId}/${date}`,
  CreateAppointment: "/appointment/create",
  GetAppointments: "/appointment/all",
  SetAppointmentState: "/appointment/approve",
  DeleteAppointment: (appointmentId) => `/appointment/${appointmentId}`,
  GetAllNotifications: "/notifications/all",
  ReadNotification: "/notifications/read",
  AddNotification: "/notifications/add",
  UploadDocument: "/storage/upload",
  DownloadDocument: (documentId) => `/storage/download/${documentId}`,
  UploadUserPicture: "/storage/user/picture",
  UploadSpecializationPicture: "storage/specialization/picture",
  GetAllUsers: "/user/all",
  RegiserDoctor: "user/register/doctor",
  LeaveReview: "/review/create",
};
