export default {
  home: "/",
  landing: "/landing",
  users: "/users",
  userDetails: "/user/:id",
  weather: "/weather",
  error: "/error",
  demo: "/demo",
  components: "/components",
  allSpecializations: "/specializations",
  profile: "/profile",
  doctors: "/doctors",
  program: "/program",
  createProgram: "/createProgram",
  appointments: "/appointments",
  notifications: "/notifications",
  manageUsers: "/list",
  createDoctor: "/createDoctor",
};
